on:
  push:

name: Build
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - name: Run Integration tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: DISPLAY=$HOST_IP npm run test
